# Source: cluster-api-byoh/templates/byoh-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 6ab847c1-a846-4a0f-ab75-165466a1192a-control-plane
  namespace: 6ab847c1-a846-4a0f-ab75-165466a1192a
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: control-plane
