---
apiVersion: v1
kind: Namespace
metadata:
  name: 6ab847c1-a846-4a0f-ab75-165466a1192a
  labels:
    name: 6ab847c1-a846-4a0f-ab75-165466a1192a
    # It bring the secret 'dacapod-argocd-config' using kubed
    decapod-argocd-config: enabled

